stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - mkdocs build --site-dir _site
  artifacts:
    paths:
      - _site

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region eu-west-2 # Your region
    - aws s3 sync ./_site/ s3://company-policies-website --delete
  dependencies:
    - build
  when: on_success